<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Help[

<!ELEMENT Help (Cmd+)>
<!ELEMENT Cmd (Parameters, Description)>
<!ELEMENT Parameters (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

<!ATTLIST Cmd
	name CDATA #REQUIRED
>
]>


<Help>
	<Cmd name="ls">
		<Parameters><![CDATA[[directory]]]></Parameters>
		<Description><![CDATA[list directory contents]]></Description>
	</Cmd>

	<Cmd name="cd">
		<Parameters><![CDATA[&lt;dirname&gt;]]></Parameters>
		<Description><![CDATA[Change working directory]]></Description>
	</Cmd>

	<Cmd name="clear">
		<Parameters></Parameters>
		<Description><![CDATA[Clear the screen]]></Description>
	</Cmd>
</Help>
